config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  root 'pages#index'

  resources :pages, only: [] do
    collection do 
      post :add_card
      post :remove_card
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :cards_decks
  has_many :decks, through: :cards_decks, source: :deck
end

app/models/cards_deck.rb
class CardsDeck < ApplicationRecord
  belongs_to :card
  belongs_to :deck
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards_decks
  has_many :cards, through: :cards_decks, source: :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @deck  = Deck.first
    @cards = Card.all - @deck.cards
  end

  def add_card
    @card = Card.find(params[:card_id])
    Deck.first.cards << @card
    redirect_to pages_index_path
  end

  def remove_card
    @card = Card.find(params[:card_id])
    CardsDeck.find_by(card_id: @card.id, deck_id: Deck.first.id).delete
    redirect_to pages_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Magic
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/pages/index.html.haml
%h1 Welcome to Magic The Gathering


%h2 Cards in #{@deck.name}
- @deck.cards.each do |card|
  = card.name
  %br
  = link_to 'Remove This Card', remove_card_pages_path(card_id: card.id), method: :post
  %br
  - form_tag do
    = select_tag 'deck_name', options_from_collection_for_select(Deck.all, "id", "name")

%h2 Cards that are not in #{@deck.name}
- @cards.each do |card|
  = card.name
  %br
  = link_to 'Add This Card', add_card_pages_path(card_id: card.id), method: :post
  %br